### ISSUE TITLE
Destroy lost connection objects acquired from mysql.connect()

### ISSUE THREAD

**Issue by Totktonada** [tarantool/mysql#31]
When a connection is acquired from a pool, lost and collected by Lua GC, its underlying connection will be closed from a GC callback. A connection that is created directly w/o a pool using `mysql.connect()` has no such GC callback, so its underlying connection will not be properly closed if a user does not call `<connection object>:close()` manually.

A fiber may store a connection in its local variable. If this fiber does not handle abnormal exit properly and, say, does not close the connection when is hit by fiber.cancel(), the underlying connection will leak.

We should test than the underlying connection is closed in the case.

**Comment by romanhabibov** [comment]
I've checked. Connection doesn't leak actually. `lua_mysql_gc(struct lua_State *L)`  is called with `collectgarbadge()`. The ticket isn't relevant. https://github.com/tarantool/mysql/blob/6f785f7f0faa6c98e376c828d1554583de505e8b/mysql/driver.c#L529

**Comment by Totktonada** [comment]
How about a test that checks that a file descriptor actually closed?
