### ISSUE TITLE
Destroy broken connection when it is put back to a pool

### ISSUE THREAD

**Issue by Totktonada** [tarantool/mysql#32]
The case: a connection is acquired from a pool, a request is made with this connection and fails, the connection is put back to the pool.

The connection is marked as broken in the case and will be discarded: a pool will not actually cache it, just count (`<pool object>.queue:put(nil)` under hood) that it may give (and create if needed) one more connection when it will be acquired. The math here looks correct. However an underlying raw connection of this 'broken' connection will not be closed neither when it put back to the pool, nor at GC (because the GC callback is removed at `<pool object>:put()` for both broken and healthy connections).

This behaviour looks as a bug. I propose to destroy the underlying connection when it is discarded at `<pool object>:put()`: i. e. close the underlying connection if it is broken.

We should test than the underlying connection is closed in the case.

**Comment by LeonidVas** [comment]
Related: https://github.com/tarantool/mysql/issues/46

**Comment by Totktonada** [comment]
I overlooked the GC callback in driver.c (only looked over init.lua):

https://github.com/tarantool/mysql/blob/830189864d4484e22954cc0bdbe3852e0b8ba407/mysql/driver.c#L689

https://github.com/tarantool/mysql/blob/830189864d4484e22954cc0bdbe3852e0b8ba407/mysql/driver.c#L525-L542

So everything should be good.
