### ISSUE TITLE
tarantool-mysql missing from 2.4 live?

### ISSUE THREAD

**Issue by ethaniel** [tarantool/mysql#40]
I tried doing `yum install tarantool-mysql` right after installing tarantool from the live repo, but I am getting `No package tarantool-mysql available`.

`yum list` doesn't show any presensce of `tarantool-mysql`, only things I am getting is:
```
tarantool-authman.noarch                 1.4.35-1.el7.centos      tarantool_2_5
tarantool-avro-schema.x86_64             3.0.5.2-1.el7            tarantool_2_5
tarantool-avro-schema-debuginfo.x86_64   3.0.5.2-1.el7            tarantool_2_5
tarantool-c.x86_64                       1.0.87-1.el7             tarantool_2_5
tarantool-c-debuginfo.x86_64             1.0.87-1.el7             tarantool_2_5
tarantool-c-devel.x86_64                 1.0.87-1.el7             tarantool_2_5
tarantool-checks.noarch                  3.0.1.2-1.el7            tarantool_2_5
tarantool-debuginfo.x86_64               1.10.3.104-1.el7         epel-debuginfo
tarantool-devel.x86_64                   2.4.2.39-1.el7           tarantool_2_5
tarantool-dump.noarch                    1.0.20-1.el7             tarantool_2_5
tarantool-expirationd.noarch             1.0.25-1.el7             tarantool_2_5
tarantool-graphql.noarch                 0.0.1.89-1.el7           tarantool_2_5
tarantool-luacheck.noarch                0.24.0.6-1.el7           tarantool_2_5
tarantool-lulpeg.noarch                  0.1.2.2-1.el7            tarantool_2_5
tarantool-memcached.x86_64               1.0.1.1-1.el7            tarantool_2_5
tarantool-memcached-debuginfo.x86_64     1.0.1.1-1.el7            tarantool_2_5
tarantool-python.noarch                  0.6.6-5.el7              tarantool_2_5
tarantool-queue.noarch                   1.0.7.0-1.el7            tarantool_2_5
tarantool-smtp.x86_64                    0.0.2.11-1.el7           tarantool_2_5
tarantool-smtp-debuginfo.x86_64          0.0.2.11-1.el7           tarantool_2_5
tarantool-try.noarch                     1.0.75-1.el7.centos      tarantool_2_5
tarantool-vshard.noarch                  0.1.16.0-1.el7           tarantool_2_5
```

**Comment by Totktonada** [comment]
Thanks for the notice!

Sure, the last commit was a long time ago: before the tarantool-2.4 repository was created.

I created the new deploy job in PR #41, but our infrastucture requires some manual actions to make the packages available via download.tarantool.org repositories. @avtikhon knows required kung fu. (The new build will appear as tarantool-mysql-2.0.44-1.el7.x86_64.rpm.)

For a while you can download and install it from our old mirror on packagecloud.io:

```sh
wget --content-disposition https://packagecloud.io/tarantool/2_4/packages/el/7/tarantool-mysql-2.0.44-1.el7.x86_64.rpm/download.rpm
yum install tarantool-mysql-2.0.44-1.el7.x86_64
```

**Comment by avtikhon** [comment]
> Thanks for the notice!
> 
> Sure, the last commit was a long time ago: before the tarantool-2.4 repository was created.
> 
> I created the new deploy job in PR #41, but our infrastucture requires some manual actions to make the packages available via download.tarantool.org repositories. @avtikhon knows required kung fu. (The new build will appear as tarantool-mysql-2.0.44-1.el7.x86_64.rpm.)
> 
> For a while you can download and install it from our old mirror on packagecloud.io:
> 
> ```shell
> wget --content-disposition https://packagecloud.io/tarantool/2_4/packages/el/7/tarantool-mysql-2.0.44-1.el7.x86_64.rpm/download.rpm
> yum install tarantool-mysql-2.0.44-1.el7.x86_64
> ```

Right, currently we use manual triggering for modules packages updates, so I run it and currently the new version 2.0.44 is available.
