### ISSUE TITLE
Error: Can't initialize character set unknown

### ISSUE THREAD

**Issue by LeonidVas** [tarantool/mysql#47]
An error occurs when trying to connect to MySQL server 8.0.21: "Error: Can't initialize character set unknown..."

**Comment by LeonidVas** [comment]
Workaround: https://github.com/pBlueG/SA-MP-MySQL/issues/203

**Comment by LeonidVas** [comment]
It looks like the connector needs to be improved https://jira.mariadb.org/browse/CONC-308

**Comment by Totktonada** [comment]
For ones who curious: [utf8mb4](https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8mb4.html), utf8 is alias for [utf8mb3](https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8.html).

**Comment by Totktonada** [comment]
What works for me on Gentoo:

```ini
[mysqld]
character-set-server = utf8  # was utf8mb4
```

```
$ mysql --version
mysql  Ver 8.0.20 for Linux on x86_64 (Gentoo Linux mysql-8.0.20)
```
